In [1]:
"""
Datasets are available at https://zenodo.org/records/6355684 
"""

'\nDatasets are available at https://zenodo.org/records/6355684 \n'

In [2]:
import sys
print(sys.version)

3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

In [3]:
from silhouette_upper_bound import upper_bound
import numpy as np
import kmedoids
from scipy.spatial.distance import squareform, pdist
from common import get_df_sampled, eval

In [ ]:
def get_distance_matrix_and_labels(df_sampled, n_classes, n_features, seed):
    """
    Help function for loading distance matrix and class labels.
    """

    # set seed
    np.random.seed(seed)

    # sample classes 
    classes = df_sampled["class"].unique()
    chosen = np.random.choice(classes, size=n_classes, replace=False)

    # Filter dataframe to those two classes
    df_sampled_n_classes = df_sampled[df_sampled["class"].isin(chosen)]
    print("Classes: " + str(df_sampled_n_classes["class"].unique()))

    # Separate data into feature vectors and class labels 
    y = df_sampled_n_classes["class"]
    X = df_sampled_n_classes.iloc[:, 0:n_features]
    X = X.to_numpy()

    print(f"Shape of feature vectors: {X.shape}. Data type: {X.dtype}")
    D = squareform(pdist(X, metric="cityblock"))

    return D, y

# 1. ALOI HSB 5x5x5

In [5]:
dataset_name = "aloi-hsb-5x5x5"
N_FEATURES = 125

In [6]:
df_sampled = get_df_sampled(dataset_name=dataset_name)
df_sampled.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,class
0,0.045401,0.001526,0.003160,0.006736,0.023887,0.172085,0.004343,0.011235,0.008873,0.003832,...,0.000411,0.000066,0.000335,0.002301,0.009011,0.006079,0.000045,"""img1""","""1/1_r280.png""",1
1,0.045225,0.000613,0.001031,0.002921,0.020752,0.173089,0.002421,0.004028,0.005229,0.005391,...,0.000271,0.000416,0.000201,0.000520,0.004795,0.011194,0.002145,"""img1""","""1/1_i230.png""",1
2,0.014931,0.000016,0.000000,0.000000,0.000301,0.130830,0.000723,0.000744,0.001067,0.020598,...,0.000120,0.000373,0.000179,0.000626,0.003092,0.012356,0.005875,"""img1""","""1/1_i150.png""",1
3,0.043287,0.001560,0.003798,0.005082,0.019194,0.170754,0.006427,0.012146,0.007935,0.003599,...,0.000330,0.000183,0.000183,0.001350,0.007388,0.009465,0.000136,"""img1""","""1/1_r305.png""",1
4,0.050345,0.001476,0.003187,0.005841,0.028332,0.177456,0.003007,0.005674,0.006933,0.004853,...,0.000543,0.000079,0.000104,0.002783,0.017675,0.003879,0.000070,"""img1""","""1/1_r210.png""",1

### n classes = 2

In [7]:
n_classes = 2

# Load data
D2, y2 = get_distance_matrix_and_labels(df_sampled=df_sampled, n_classes=n_classes, n_features=N_FEATURES, seed=872)
ub = upper_bound(D2)

Classes: [155 389]
Shape of feature vectors: (200, 125). Data type: float64

In [8]:
# PAMSIL
eval(D2, y2, (kmedoids.pamsil(diss=D2, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 94
K = 2
ASW = 0.6686712504441235
ub = 0.8989414824507823
WCRE = 0.25615708753240934
uba = 0.7145427525388146
wcre = 0.06419700141343099
Adjusted Rand Index vs. true labels: 0.883
Adjusted Mutual Info vs. true labels: 0.834

2&94&0.883&0.834&0.669&0.899&0.256&0.715&0.064

In [9]:
# FastMSC
eval(D2, y2, (kmedoids.fastmsc(diss=D2, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 94
K = 2
ASW = 0.6686712504441235
ub = 0.8989414824507823
WCRE = 0.25615708753240934
uba = 0.7145427525388146
wcre = 0.06419700141343099
Adjusted Rand Index vs. true labels: 0.883
Adjusted Mutual Info vs. true labels: 0.834

2&94&0.883&0.834&0.669&0.899&0.256&0.715&0.064

In [10]:
# DynMSC
eval(D2, y2, (kmedoids.dynmsc(diss=D2, medoids=10, random_state=42).labels + 1), ub)

Min cluster size = 1
K = 8
ASW = 0.6467565067151209
ub = 0.8989414824507823
WCRE = 0.2805354749545322
uba = 0.8989414824507823
wcre = 0.2805354749545322
Adjusted Rand Index vs. true labels: 0.876
Adjusted Mutual Info vs. true labels: 0.820

8&1&0.876&0.820&0.647&0.899&0.281&0.899&0.281

### n classes = 5

In [11]:
n_classes = 5

# Load data
D5, y5 = get_distance_matrix_and_labels(df_sampled=df_sampled, n_classes=n_classes, n_features=N_FEATURES, seed=25)
ub = upper_bound(D5)

Classes: [ 50 289 689 699 776]
Shape of feature vectors: (500, 125). Data type: float64

In [12]:
# PAMSIL
eval(D5, y5, (kmedoids.pamsil(diss=D5, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 24
K = 5
ASW = 0.47806841794290383
ub = 0.8985129984767883
WCRE = 0.46793377641352624
uba = 0.7623112234093785
wcre = 0.37286976334314026
Adjusted Rand Index vs. true labels: 0.675
Adjusted Mutual Info vs. true labels: 0.751

5&24&0.675&0.751&0.478&0.899&0.468&0.762&0.373

In [13]:
# FastMSC
eval(D5, y5, (kmedoids.fastmsc(diss=D5, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 19
K = 5
ASW = 0.4732522931811366
ub = 0.8985129984767883
WCRE = 0.47329388224386126
uba = 0.7781139828984562
wcre = 0.3917956705799284
Adjusted Rand Index vs. true labels: 0.654
Adjusted Mutual Info vs. true labels: 0.723

5&19&0.654&0.723&0.473&0.899&0.473&0.778&0.392

In [14]:
# DynMSC
eval(D5, y5, (kmedoids.dynmsc(diss=D5, medoids=10, random_state=42).labels + 1), ub)

Min cluster size = 28
K = 2
ASW = 0.41630960438602654
ub = 0.8985129984767883
WCRE = 0.5366682450985363
uba = 0.7518455007784354
wcre = 0.44628304092397486
Adjusted Rand Index vs. true labels: 0.001
Adjusted Mutual Info vs. true labels: 0.009

2&28&0.001&0.009&0.416&0.899&0.537&0.752&0.446

# 2. ALOI HSB 14x6x6

In [15]:
dataset_name = "aloi-hsb-14x6x6"
N_FEATURES = 504

In [16]:
df_sampled = get_df_sampled(dataset_name=dataset_name)
df_sampled.head()

,0,1,2,3,4,5,6,7,8,9,...,497,498,499,500,501,502,503,504,505,class
0,0.010166,0.000084,0.000045,0.000079,0.000129,0.001203,0.034017,0.000197,0.000805,0.001309,...,0.000014,0.000061,0.001341,0.003411,0.009531,0.002423,0.000007,"""img1""","""1/1_r280.png""",1
1,0.010283,0.000054,0.000068,0.000059,0.000061,0.001610,0.032213,0.000167,0.000158,0.000174,...,0.000411,0.000050,0.000251,0.001487,0.007643,0.007541,0.000925,"""img1""","""1/1_i230.png""",1
2,0.004230,0.000000,0.000000,0.000000,0.000000,0.000000,0.029790,0.000052,0.000036,0.000009,...,0.000434,0.000043,0.000488,0.001069,0.005098,0.010948,0.003913,"""img1""","""1/1_i150.png""",1
3,0.010306,0.000093,0.000070,0.000079,0.000090,0.001072,0.032052,0.000278,0.000963,0.000726,...,0.000059,0.000086,0.000554,0.002062,0.009861,0.005012,0.000016,"""img1""","""1/1_r305.png""",1
4,0.011635,0.000131,0.000149,0.000156,0.000104,0.001216,0.036904,0.000416,0.000450,0.000877,...,0.000043,0.000084,0.001225,0.005269,0.016473,0.000328,0.000045,"""img1""","""1/1_r210.png""",1

### n classes = 2

In [17]:
n_classes = 2

# Load data
D2, y2 = get_distance_matrix_and_labels(df_sampled=df_sampled, n_classes=n_classes, n_features=N_FEATURES, seed=872)
ub = upper_bound(D2)

Classes: [155 389]
Shape of feature vectors: (200, 504). Data type: float64

In [18]:
# PAMSIL
eval(D2, y2, (kmedoids.pamsil(diss=D2, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 94
K = 2
ASW = 0.6402911008561487
ub = 0.8788585652873633
WCRE = 0.2714514870242055
uba = 0.6945871926817037
wcre = 0.07817030373958575
Adjusted Rand Index vs. true labels: 0.883
Adjusted Mutual Info vs. true labels: 0.834

2&94&0.883&0.834&0.640&0.879&0.271&0.695&0.078

In [19]:
# FastMSC
eval(D2, y2, (kmedoids.fastmsc(diss=D2, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 92
K = 2
ASW = 0.6392995421986787
ub = 0.8788585652873633
WCRE = 0.27257972164196315
uba = 0.7021548197694213
wcre = 0.08951769011766306
Adjusted Rand Index vs. true labels: 0.846
Adjusted Mutual Info vs. true labels: 0.795

2&92&0.846&0.795&0.639&0.879&0.273&0.702&0.090

In [20]:
# DynMSC
eval(D2, y2, (kmedoids.dynmsc(diss=D2, medoids=10, random_state=42).labels + 1), ub)

Min cluster size = 1
K = 9
ASW = 0.6439019391799796
ub = 0.8788585652873633
WCRE = 0.26734293251219454
uba = 0.8788585652873633
wcre = 0.26734293251219454
Adjusted Rand Index vs. true labels: 0.856
Adjusted Mutual Info vs. true labels: 0.776

9&1&0.856&0.776&0.644&0.879&0.267&0.879&0.267

### n classes = 5

In [21]:
n_classes = 5

# Load data
D5, y5 = get_distance_matrix_and_labels(df_sampled=df_sampled, n_classes=n_classes, n_features=N_FEATURES, seed=25)
ub = upper_bound(D5)

Classes: [ 50 289 689 699 776]
Shape of feature vectors: (500, 504). Data type: float64

In [22]:
# PAMSIL
eval(D5, y5, (kmedoids.pamsil(diss=D5, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 24
K = 5
ASW = 0.47325691900644107
ub = 0.8880079850168976
WCRE = 0.46705781142560826
uba = 0.752391481497908
wcre = 0.370996441820086
Adjusted Rand Index vs. true labels: 0.670
Adjusted Mutual Info vs. true labels: 0.739

5&24&0.670&0.739&0.473&0.888&0.467&0.752&0.371

In [23]:
# FastMSC
eval(D5, y5, (kmedoids.fastmsc(diss=D5, medoids=n_classes, random_state=42).labels + 1), ub)

Min cluster size = 23
K = 5
ASW = 0.47093971569729165
ub = 0.8880079850168976
WCRE = 0.4696672511471501
uba = 0.7550342275774208
wcre = 0.37626706380141983
Adjusted Rand Index vs. true labels: 0.676
Adjusted Mutual Info vs. true labels: 0.754

5&23&0.676&0.754&0.471&0.888&0.470&0.755&0.376

In [24]:
# DynMSC
eval(D5, y5, (kmedoids.dynmsc(diss=D5, medoids=10, random_state=42).labels + 1), ub)

Min cluster size = 20
K = 6
ASW = 0.4721924482042574
ub = 0.8880079850168976
WCRE = 0.4682565290274139
uba = 0.7637853692700396
wcre = 0.3817733787496632
Adjusted Rand Index vs. true labels: 0.678
Adjusted Mutual Info vs. true labels: 0.746

6&20&0.678&0.746&0.472&0.888&0.468&0.764&0.382